name: setup-smt
description: Download and provides the z3 and cvc5 SMT solvers
author: Alexander Weigl

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  z3Version:
    description: Version of Z3 to install
    required: true
    default: '4.13.3'

  cvc5Version:
    description: Version of CVC5 to install
    required: true
    default: '1.2.1'

runs:
  using: node20
  main: dist/index.js
